---
dist: trusty
sudo: required

language: go
go:
  - 1.10.x

addons:
  apt:
    packages:
      - npm

go_import_path: github.com/ligato/osseus

git:
  depth: 1

before_install:
  - go get -v github.com/mattn/goveralls

script:
  - make dep-check
  - make client-install
  - make
  - $GOPATH/bin/goveralls -service=travis-ci