---

# Frontend Service
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    nodePort: 31100

---

# Server Service
apiVersion: v1
kind: Service
metadata:
  name: node-server
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
  - port: 8000
    targetPort: 8000
    nodePort: 31101

---

# Frontend Deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: osseus-frontend
  labels:
    app: frontend
spec:
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers: 
        - name: client
          image: anthonydevelops/front_end:dev
          ports:
            - containerPort: 3000
            - containerPort: 8000

---

# Agent Service
apiVersion: v1
kind: Service
metadata:
  name: agent-svc
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 9191
    targetPort: 9191
    protocol: TCP
    nodePort: 31102

---
# Agent Deployment
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: osseus-backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers: 
        - name: agent
          image: anthonydevelops/agent:dev
          ports:
            - containerPort: 9191

---

# KV Deployment
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: osseus-etcd
spec:
  serviceName: osseus-etcd
  selector:
    matchLabels:
      app: osseus-etcd
  template:
    metadata:
      labels:
        app: osseus-etcd
    spec:
      containers:
        - name: etcd
          image: quay.io/coreos/etcd:v3.3.8
          env:
            - name: ETCDCTL_API
              value: "3"
          command:
            - /bin/sh
          args:
            - -c
            - /usr/local/bin/etcd --name=osseus-etcd --data-dir=/var/etcd/osseus-data
              --advertise-client-urls=http://0.0.0.0:2379 --listen-client-urls=http://0.0.0.0:2379
          ports:
            - containerPort: 2379
              protocol: TCP

---

# KV Service
apiVersion: v1
kind: Service
metadata:
  name: etcd-svc
  labels:
    app: osseus-etcd
spec:
  type: NodePort
  ports:
  - port: 2379
    protocol: TCP
    targetPort: 2379
    nodePort: 31103
  selector:
    app: osseus-etcd

---

# This config map contains ETCD configuration for connecting to the osseus-etcd defined above.
apiVersion: v1
kind: ConfigMap
metadata:
  name: osseus-etcd-cfg
data:
  etcd.conf: |
    insecure-transport: true
    dial-timeout: 10000000000
    allow-delayed-start: true
    endpoints:
      - "__HOST_IP__:2379"

---

# Setup Ingress 
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: osseus-rules
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /
        backend:
          serviceName: ui
          servicePort: 3000
      - path: /server
        backend:
          serviceName: node-server
          servicePort: 8000
      - path: /agent
        backend:
          serviceName: agent-svc
          servicePort: 9191
      - path: /etcd
        backend:
          serviceName: etcd-svc
          servicePort: 2379
